cc_binary(
  name = "example",
  srcs = [
    "example.c",
  ],
  deps = [
    "//:zlib",
  ],
)

cc_binary(
  name = "infcover",
  srcs = [
    "infcover.c",
  ],
  deps = [
    "//:zlib",
  ],
)

cc_binary(
  name = "minigzip",
  srcs = [
    "minigzip.c",
  ],
  deps = [
    "//:zlib",
  ],
)
